=== BackupTheBerlios/osdev/osxml/dtd/guide.dtd
<!-- $Id: guide.dtd,v 1.1 2002/07/02 07:43:37 zhware Exp $ -->

<!-- Grab a bunch of additional Latin characters courtesy of Norman -->
<!-- Walsh's extraction of the ISO 8879 set for DocBook XML. -->
<!ENTITY % ISOlat1.module "INCLUDE">
<![%ISOlat1.module;[
<!ENTITY % ISOlat1 PUBLIC
"ISO 8879:1986//ENTITIES Added Latin 1//EN//XML"
"iso-lat1.ent">
%ISOlat1;
<!--end of ISOlat1.module-->]]>
<!ENTITY nbsp "&#160;">		<!-- &nbsp; -->
<!ENTITY copy "&#169;">		<!-- (c) -->

<!ENTITY  % style.class	"b|box|brite|c|codenote|comment|e|i|path">
<!ENTITY  % link.class	"uri|homepage|email|mail">
<!ENTITY  % logic.class	"copyright|figure|fig|img|br|note|impo|warn|pre|p|table|ul|ol|new">
<!ENTITY  % all.class	"%logic.class;|%style.class;|%link.class;">

<!ELEMENT guide		(title, subtitle?, author+, abstract, version, date, copyright?, chapter+)>
<!ATTLIST guide		link CDATA #IMPLIED>
<!ELEMENT title		(#PCDATA|%style.class;)*>
<!ELEMENT subtitle	(#PCDATA)>
<!ELEMENT author	(#PCDATA|email|mail)*>
<!ATTLIST author	title CDATA #IMPLIED
                	homepage CDATA #IMPLIED>
<!ELEMENT abstract	(#PCDATA)>
<!ELEMENT version	(#PCDATA)>
<!ELEMENT date		(#PCDATA)>
<!ELEMENT copyright	(#PCDATA)>
<!ELEMENT chapter	(title, section+)>
<!ATTLIST chapter	id CDATA #IMPLIED>
<!ELEMENT section	(title?, body)>
<!ELEMENT body		(%all.class;)*>
<!ELEMENT figure	EMPTY>
<!ATTLIST figure	caption CDATA #IMPLIED
			short CDATA #IMPLIED
			link CDATA #REQUIRED>
<!ELEMENT fig		EMPTY>
<!ATTLIST fig		short CDATA #IMPLIED
			linkto CDATA #IMPLIED
			link CDATA #REQUIRED>
<!ELEMENT img		EMPTY>
<!ATTLIST img		src CDATA #REQUIRED>
<!ELEMENT br		(#PCDATA)>
<!ELEMENT new		(#PCDATA)>
<!ELEMENT note		(#PCDATA|%all.class;)*>
<!ATTLIST note		caption CDATA #IMPLIED>
<!ELEMENT impo		(#PCDATA|%all.class;)*>
<!ELEMENT warn		(#PCDATA|%all.class;)*>
<!ELEMENT pre		(#PCDATA|%all.class;)*>
<!ATTLIST pre		caption CDATA #IMPLIED
			link CDATA #IMPLIED>
<!ELEMENT p		(#PCDATA|%all.class;)*>
<!ELEMENT table		(tr+)>
<!ELEMENT tr		(th+|ti+)>
<!ELEMENT th		(#PCDATA|%all.class;)*>
<!ELEMENT ti		(#PCDATA|%all.class;)*>
<!ELEMENT ul		(li+)>
<!ELEMENT ol		(li+)>
<!ELEMENT li		(#PCDATA|%all.class;)*>

<!--STYLE TAGS-->
<!ELEMENT b		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT brite		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT box		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT c		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT codenote	(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT comment	(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT e		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT i		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT path		(#PCDATA|%style.class;|%link.class;)*>

<!--LINK TAGS-->
<!ELEMENT uri		(#PCDATA|%style.class;)*>
<!ATTLIST uri		link CDATA #IMPLIED>
<!ELEMENT homepage	(#PCDATA|%style.class;)*>
<!ELEMENT mail		(#PCDATA|%style.class;)*>
<!ATTLIST mail		link CDATA #REQUIRED>
<!ELEMENT email		(#PCDATA|%style.class;)*>
<!ATTLIST email		link CDATA #IMPLIED>

=== BackupTheBerlios/osdev/osxml/xml/spinlock_part2.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd">
<!-- $Id: spinlock_part2.xml,v 1.1 2002/07/02 07:43:39 zhware Exp $ -->

<guide link="spinlock_part2">
<title>Spinlocks</title>
<subtitle>Part II</subtitle>
<author>
<email link="mrieker@o3one.org">Mike Rieker</email>
<title>author</title>
<homepage>http://www.o3one.org/</homepage>
</author>
<date>$Date: 2002/07/02 07:43:39 $</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2002/07/02 07:43:39 $</copyright>

<keywordset>
   <keyword>osdev</keyword>
   <keyword>Mike Rieker</keyword>
   <keyword>scheduling</keyword>
   <keyword>spinlock</keyword>
</keywordset>

<abstract>
Now after you get into this stuff, you may find that you have to have more
than one spinlock at a time.
</abstract>

<chapter id="simultaneous">
<title>Simultaneous spinlocks</title>
<section>
<body>

<p>
Now after you get into this stuff, you may find that you have to have more 
than one spinlock at a time.  This can lead to problems.  Consider this:
<pre>
Routine A:

  lock spinlock X
  maybe do some work
  lock spinlock Y
  do some more work
  unlock spinlock Y
  unlock spinlock X


And Routine B:

  lock spinlock Y
  maybe do some work
  lock spinlock X
  do some more work
  unlock spinlock X
  unlock spinlock Y
</pre>
</p>
<p>
So CPU #1 comes along and starts <c>routine A</c>, while CPU #2 starts <c>routine B</c>.  Well, they'll 
never finish, because CPU #1 will be waiting for CPU #2 to release <c>spinlock Y</c> and CPU #2 
will be waiting for CPU #1 to release <c>spinlock X</c>.
</p>
<p>
So we have another simple rule:
<impo>
When locking more than one spinlock, they must always be locked in the same order.
</impo>
</p>
<p>
So for our example, both routines need to be changed so that they either both lock X then 
Y or they both lock Y then X.  You may be thinking, 'I might not be able to do that in ALL 
cases!'  Easy to fix, replace the two spinlocks with one, say Z.
</p>
<p>
Now I am terrible at checking to make sure I do everything in order.  Computers are good 
at that sort of thing.  So rather than just using an 'int' for my spinlocks, I use a struct 
as follows:
<pre>
  typedef struct { char spinlock_flag;            // the usual 0=unlocked, 1=locked
                   unsigned char spinlock_level;  // 'locking' order
                 } Spinlock;
</pre>
</p>
<p>
Then I have a spinlock_wait routine that checks to make sure my new spinlock's level is .gt. 
the last spinlock's level that was locked by this cpu.  If I try to do it out of order, the 
routine panics/BSOD's on the spot.
</p>

</body>
</section>
</chapter>

<chapter id="interrupts">
<title>Interrupts</title>
<section>
<body>

<p>
Another question you may wonder, must I always inhibit hardware interrupt delivery when I 
have a spinlock?
</p>
<p>
No.  Only if the data being worked with can also be accessed by an interrupt routine.  And 
then, you only have to disable those interrupts that have access to it.
</p>
<p>
For example, I don't allow my interrupt routines to do malloc's.  So the malloc routine can 
run with interrupts enabled, even when it has the spinlock.  Same with pagetables, disk cache 
pages, and other stuff like that.
</p>
<p>
You must, however, block any pre-emptive scheduling while you have a any spinlock.  Or at 
least, you will make things *very* complicated if you don't.
</p>
<p>
So I ended up with several 'classes' of spinlocks:
<ul>
  <li>low priority - these run with all hardware interrupt delivery enabled
  interrupt level - there is one per IRQ level.  IRQ 0 is the highest, IRQ 7 is the lowest.
                    when one of these is set on a cpu, it inhibits that IRQ and any lower priority interrupts</li>
  <li>high priority - these run with all hardware interrupt delivery inhibited</li>
</ul>
</p>
<p>
So if a cpu has one of the low priority spinlocks, it is running with hardware interrupt delivery 
enabled (but the pre-emptive scheduler is disabled).
</p>
<p>
There is one spinlock per interrupt level.  For example, the keyboard driver uses IRQ 1.  So whenever the 
keyboard interrupt routine is active, I have the cpu take the <c>IRQ 1 spinlock</c>.  Whenever the main keyboard 
driver routine is accessing data that the interrupt routine would access, I take the <c>IRQ 1 spinlock</c>.  So 
it in essence acts as a 'inhibit interrupt delivery' mechanism that works across cpu's in an SMP system.
</p>
<p>
The high-priority interrupts block all interrupt delivery on the cpu.  These are used for routines (like 
wake_a_thread) that need to be callable from any interrupt level.
</p>

</body>
</section>
</chapter>

<chapter id="performance">
<title>Performance</title>
<section>
<body>

<p>
This is a big thing about spinlocks.  It's easy to make your performance go to pot with 
poor use of spinlocks.
</p>
<p>
Consider that you can *theoretically* use just *one* spinlock, period.  Whenever you enter 
kernel mode, inhibit all interrupt delivery and set your one-and-only spinlock.  When you 
leave kernel mode, release the spinlock then enable interrupt delivery.  Great!
</p>
<p>
Well, you can imagine then, that what you end up with is having just one cpu doing anything 
useful at a time in kernel mode, while the other(s) just grind away spinning.  Really bad!
</p>
<p>
So what you do is try to come up with as many spinlocks as you can.  Above I mentioned that 
you must combine X and Y if you have a case where you must set X then Y and another case where 
you must set Y then X.  So now you have two limits to work with:
<ul>
<li>Too few spinlocks and you have poor performance</li>
<li>Too many spinlocks and you violate the ordering</li>
</ul>
</p>
<p>
Here's where the creativity comes in, working with those two limits to 
maximize performance.  Strive to eliminate as much spinning as possible.
</p>
<p>
How does one measure spinlock performance?  Make an array of counters like this:
<pre>
  static int spin_counts[256];
</pre>
</p>
<p>
Then increment <c>spin_counts[spinlock_level]</c> each time the 'test_and_set' fails.  After a while 
of running stuff, find which <c>spinlock_level</c> has big counts (compared to the others).  Try to 
break that smplock down into smaller ones if you can figure out how to.
</p>

</body>
</section>
</chapter>

<chapter id="summary">
<title>Summary</title>
<section>
<body>

<p>
They may seem sort of nebulous to begin with.  But after you work with them, application 
becomes very scientific.  I hope this little tutorial has helped clear up some issues and 
gives you confidence.
</p>
<p>
I have some more practical stuff at <uri>http://www.o3one.org/smplocks.html</uri> if you're still interested.
</p>

</body>
</section>
</chapter>

</guide>

=== BackupTheBerlios/osdev/osxml/xml/console_io.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd">
<!-- $Id: console_io.xml,v 1.1 2002/07/02 07:43:38 zhware Exp $ -->

<guide link="console_io">
<title>Console I/O via memory moves</title>
<author>
<email link="sft3236@post.netlink.se">Jens Olsson</email>
<title>author</title>
</author>
<date>$Date: 2002/07/02 07:43:38 $</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2002/07/02 07:43:38 $</copyright>

<keywordset>
   <keyword>osdev</keyword>
   <keyword>Jens Olsson</keyword>
   <keyword>user interface</keyword>
   <keyword>console</keyword>
   <keyword>GUI</keyword>
</keywordset>

<abstract>
If you are writing a text based OS you will need a way to output text in text mode. Even though you can do this via BIOS interrupts, memory moves will lead to a performance increase and will give you more control.
</abstract>

<chapter id="mmap">
<title>Memory mapping</title>
<section>
<body>

<p>
The top left character of the screen is stored at physical address <c>0xB8000</c> (<c>0xB800:0x0</c> real mode address) by default and the rest of the characters are stored in order with increasing memory address. 
E.g. Character 0, 0 is stored at <c>0xB8000</c>, character 1, 0 is stored at <c>0xB8002</c> and character 0, 1 is stored at <c>0xB80A0</c>. 
As you probably notice each character takes up 2 bytes of memory, which is because each character contains a character byte and an attribute byte. The character byte contains the ASCII value and the attribute byte contains foreground colour, background colour and sometimes a blink option. The following real mode example shows how to print a black on green A at position 0, 0 of your screen. All examples in this document are in NASM syntax.
</p>
<p>
<pre>
MOV AX, 0xB800
MOV GS, AX
MOV [GS:0x0], WORD 'A '
</pre>
</p>

</body>
</section>
</chapter>

<chapter id="cursor">
<title>Move the cursor</title>
<section>
<body>

<p>
If you write your text directly to the memory you will notice that the blinking cursor does not move with the text written. 
This you will have to do your own by using 2 I/O ports (<c>0x3D4</c> and <c>0x3D5</c>). 
<c>0x3D4</c> is the "Register index" port. 
We send the number of the register we want to change to this port, then we send the data to port <c>0x3D5</c>. 
The register indexes we will need are <c>0xE</c> and <c>0xF</c>, which together forms a 16-bit register, containing the position of the cursor.
</p>

<p>
Here follows an example of a move cursor function:
<pre link="cursor.asm">
MOVECURSOR:
;BX = New cursor pos
PUSH DX
PUSH AX
PUSH BX
MOV DX, 0x3D4 ;Hardware Cursor RegIndex Port
MOV AL, 0xF      ;Make Hardware Cursor Low reg available at 0x3D5
OUT DX, AL
INC DX ;Hardware Cursor RegData Port
MOV AL, BL
OUT DX, AL ;Write Actual Cursor Low reg
DEC DX ;Hardware Cursor RegIndex Port
MOV AL, 0xE ;Make Hardware Cursor High reg available at 0x3D5
OUT DX, AL
INC DX ;Hardware Cursor RegData Port
MOV AL, BH
OUT DX, AL ;Write Actual Cursor High reg
POP BX
POP AX
POP DX
RET
</pre>
</p>

</body>
</section>
</chapter>

</guide>

=== BackupTheBerlios/osdev/osxml/xml/authors.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd">
<!-- $Id: authors.xml,v 1.1 2002/07/02 07:43:38 zhware Exp $ -->

<guide link="authors">
<title>OS XML Documents Authors Guide</title>
<author>
<email link="sto@zhware.net">Stoyan Zhekov</email>
</author>
<date>$Date: 2002/07/02 07:43:38 $</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2002/07/02 07:43:38 $</copyright>

<keywordset>
   <keyword>osdev</keyword>
   <keyword>Stoyan Zhekov</keyword>
   <keyword>XML</keyword>
   <keyword>documents</keyword>
   <keyword>authors</keyword>
   <keyword>guide</keyword>
</keywordset>

<abstract>
Small HOWTO for the authors of OS Development XML documentation (OS XML).
</abstract>

<chapter id="intro">
<title>Introduction</title>
<section>
<body>
<p>
The project is by the people at <uri>news:alt.os.development</uri> and its target is to help all who are interested in OS Development.
The OS XML contains a collection of documents written by various OS developers
around the world.
Anyone is welcome to contribute with documents they have written. 
The main part of project are the XML documents in CVS repository.
</p>
</body>
</section>
</chapter>

<chapter id="format">
<title>Document format</title>
<section>
<body>
<p>
All documents are written in subset of XML, similar to <uri link="http://www.gentoo.org/doc/xml-guide.html">Gentoo Guide XML</uri>. Read this page - there are
examples for the most used XML tags.
In the OS XML distribution is included  <uri link="template.html">template file</uri> to ilustrate OS XML features.
</p>
<p>
<note>
<b>Notes:</b>
<p>
<ul>
<li><c>@link attribute</c> in the <c>&lt;guide&gt; tag</c> contain XML document
<b>filename without extension</b>. It is used for forming <c>other formats:</c>
links.</li>
<li>Use <c>$ Date $</c> and <c>$ Revision $</c> CVS keywords in <c>&lt;date&gt;</c> and <c>&lt;version&gt;</c> tags. They will be replaced with actual values when
document is inserted in the CVS repository.</li>
<li>Table of Content (TOC) for the document with links to chapter headers is
generated automaticaly.</li>
<li>Links to code listings are generated automaticaly.</li>
<li>You need to escape HTML characters in the source codes. You can put link in the source listing caption to the original source code.</li>
</ul>
</p>
</note>
</p>
</body>
</section>
<section>
<title>Keywords order</title>
<body>
These is <b>&lt;keywordset&gt;</b> section in the XML guides. It help
documents to be properly classified by keywords. The other possibility is
defined some categories maybe.
The defined order is not 100% required, it is just important for good documentation:
<ol>
<li>osdev -- define document as OS Development document</li>
<li>Author Name</li>
<li>Category -- common, devices, kernel, memory, sheduling, user interface</li>
<li>Others ... -- some keywords, specific for the given document</li>
</ol>
</body>
</section>
</chapter>

<chapter id="sources">
<title>Including source codes</title>
<section>
<body>
<p>
Like a general rules:
<impo>
<ul>
<li>If the source is small (&lt; 10 lines) put in directrly in the XML</li>
<li>If the source is between 10 and 30 lines, upload it to the CVS repository,
and use the <c>&lt;pre link="src/..."&gt;</c> tag with relative link and entity,
like described below</li>

<li>If the source is too big or it is some long specification, put it on some
web server, and in the XML document just use <b>absolute link</b> to it.</li>
</ul>
</impo>
</p>
<p>
It is important to mention, that if you decide to include some source code
in XML documents, all HTML special characters (&gt;, &lt; , &amp; etc.) need
to be <b>escaped</b>. For this you can use included in the CVS repocitory
(directory <path>tools/</path>)<c>src_esc</c>i or some extrnal tool. 
If you also want to make some syntax highlighting take a look at 
<uri link="http://user.cs.tu-berlin.de/~schintke/x2html">Source to .html converters page</uri>.
</p>
<p>
<ol>
<li>Escape all sources from the <path>src/</path> directory. Put escaped sources
in some other directory (for example <path>src_esc/</path> and let's the names
to be <path>original file name + .esc extension</path>. So
<pre>
src/hello.c -&gt; src_esc/hello.c.esc
src/linearfp.c -&gt; src_esc/linearfp.c.esc
...
</pre>
</li>
<li>In the beginning of your XML document put <b>entities</b>, defining path to escaped sources, you want to include. So the usual DOCTYPE declaration:
<pre>
&lt;!DOCTYPE guide SYSTEM "../dtd/guide.dtd"&gt;
</pre>
will become:
<pre>
&lt;!DOCTYPE guide SYSTEM "../dtd/guide.dtd"
[
  &lt;!ENTITY hello.c SYSTEM "../src_esc/hello.c.esc"&gt;
]&gt;
</pre>
</li>
<li>From this point everywhere in the document, where you want to include
source code, just put <c>&amp;hello.c;</c> entity:
<pre>
&lt;pre link="src/hello.c"&gt;
&amp;hello.c;
&lt;/pre&gt;
</pre>
</li>
<li>On the conversion step XSLT will replace all entities with secaped source codes</li>
</ol>
</p>
</body>
</section>
</chapter>

<chapter id="files">
<title>Directories Structure</title>
<section>
<body>
<p>
The distribution is divided in the following directories:
<ul>
<li><path>dtd/</path> -- contain DTD file for the XML</li>
<li><path>css/</path> -- several Cascade Style Sheets (.css) files for the HTML
</li>
<li><path>xsl/</path> -- xml-to-html etc. XSLT files
 <note>
 xml-to-txt processing in the moment is done by HTML-to-TXT conversion with
 <c>lynx console browser</c>. Maybe in the future there will be xml-to-txt XSLT.
 </note>
</li>
<li><path>xml/</path> -- OS Development documents in XML format
</li>
<li><path>img/</path> -- all images, used in the documents go to this directory.<note>
Use relative links to images in your documents. For example:
<pre>
&lt;fig link="img/thumb1.jpg" linkto="img/image1.jpg short="screenshot" /&gt;
</pre>
</note>
</li>
<li><path>src/</path> -- all source codes, used in the documents.
<note>
You need to escape HTML characters in your documents (&amp;, &gt;, &lt; etc.).
Source files however can not need to be changed. <e>TODO: something to make XML-ready sources (escape characters, maybe syntax highlight etc.)</e>.<br/>
Use relative links to source codes in your documents. For example:
<pre>
&lt;pre caption="Hello world" link="src/hello.c"&gt;
</pre>
</note>
</li>
<li><path>tools/</path> -- some useful tools
<ul>
<li><c>os_sync</c> -- syncronize local and remote documents via rsync</li>
<li><c>xml2all</c> -- convert one document from XML to several other formats</li>
<li><c>doit</c> -- use the scripts above to convert and upload all documents.</li>
</ul>
</li>
</ul>
</p>
</body>
</section>
</chapter>

<chapter id="cvs">
<title>Working with CVS</title>
<section>
<body>
<p>
Everybody who want to contribute to the project will need basic CVS knowledge. 
If you haven't experience with CVS see <uri link="http://www.openbg.net/sto/oswiki/moin.cgi/ConcurrentVersionsSystem">ConcurrentVersionsSystem OS Wiki page</uri>.
</p>
<p>
You need to register yourself on <uri link="https://developer.berlios.de/account/register.php">BerliOS developer pages</uri>. The name of project is:
<uri link="http://developer.berlios.de/projects/osdev/">Os Development</uri>.
For details about using CVS check <uri>http://developer.berlios.de/cvs/?group_id=430</uri>.
</p>
<p>
Some frequently use commands:
<pre>
* <c>cvs -d:ext:&lt;yourname&gt;@cvs.osdev.berlios.de:/cvsroot/osdev co osxml</c> -- get everything from the repository
* <c>cd exported/files/; cvs update</c> -- update your local documents copy
<warn>
Please do this everytime before commiting. This will prevent commit conflicts.
</warn>
* <c>cd exported/files/; cvs diff</c> -- differences between CVS repository and you local copy od documents
* <c>cd exported/files/; cvs commit -m "I change something"</c> -- commit changes to repository
</pre>
</p>
<p>
There is also <uri link="http://cvs.berlios.de/cgi-bin/cvsweb.cgi/?cvsroot=osdev">CVSWeb access to the repository</uri>.
</p>
</body>
</section>

</chapter>

</guide>

=== BackupTheBerlios/osdev/osxml/xml/tty.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd"
[ 
   <!ENTITY glass.c SYSTEM "../src_esc/glass.c.esc">
]>
<!-- $Id: tty.xml,v 1.1 2003/02/05 04:46:24 zhware Exp $ -->

<guide link="tty">
<title>How to write a TeleType (tty) device - Part I</title>
<author>
<email link="nospam777@freemail.hu">Viktor Peter Kovacs (KVP)</email>
</author>
<date>05-Feb-2003</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2003/02/05 04:46:24 $</copyright>

<keywordset>
<keyword>osdev</keyword>
<keyword>Viktor Peter Kovacs (KVP)</keyword>
<keyword>XML</keyword>
<keyword>devices</keyword>
<keyword>tty</keyword>
<keyword>teletype</keyword>
</keywordset>

<abstract>
This tutorial will describe how to implement a classical tty on a display
device, that implements a byte array based text screen, like the vga display
adapter of the pc.
</abstract>

<chapter id="intro">
<title>Introduction</title>
<section>
<body>
<p>
 The classical console based user interface is part of most operating systems.
This device was originally implemented in dedicated hardware, communicating
with the operating system through a serial cable or other byte stream based
data transfer method.<br/>
 In case of modern personal computers, where each system has a keyboard and
a display integrated, there is a need to replicate the classical terminal
based interface, and optionally extend its capabilites, by adding multiple
emulated terminals to the system.<br/>
 The interface of an emulated terminal is still the classic byte stream,
often implemented as a file. The basic interface contains only standard
single character ascii codes, and implements the functionality of a common
mechanical typewriter. These codes are enough to provide standard i/o
functionality, but not to allow more complex screen operations.
</p>
<p>
 This tutorial will describe how to implement a classical tty on a display
device, that implements a byte array based text screen, like the vga display
adapter of the pc. There are methods to use multiple display pages, and to
have hardware scrolling, but it complicates the software and imposes hardware
limitations. Because of this, I assume a single byte array based display and
minimize the use of hardware features.
</p>
<p>
 On the pc, this memory region starts at <c>0xb8000</c> linear (<c>0xb0000</c> on monochrome
cards) and cosists of 2 bytes per charcter. The dimensions depend on the
display mode, and could be: <c>80x25</c>, <c>80x50</c>, <c>80x43</c>, <c>132x50</c>, etc. For the mode
<c>0x03</c>, we have <c>80x25</c>. This could be represented as an array of words. It looks
like this: unsigned short int screen[80*25]; in c. The 1st byte of the 16 bit
word contains the character, the other one is the color.
</p>
</body>
</section>
</chapter>

<chapter id="implement">
<title>Implementation</title>
<section>
<body>
<p>
 Let&apos;s see an example code for a single, classic, glass tty. This means, that
we will only implement a few control characters, and not the functionality of
a full blown ansi terminal.
</p>
<p>
<pre caption="glass tty" link="src/glass.c">
&glass.c;
</pre>
</p>
<p>
 This code could be extended to have a <c>tty_setmode()</c> function, so there would
be a mechanism to set up the video card and the tty. The function should just
call <c>vga_setmode()</c> and <c>tty_setup()</c>, according to the selected mode&apos;s actual
parameters.
</p>
<p>
Finally, the vga color palette bit assignements:
<pre>
   0bIRGBirgb where:
    b : text blue
    g : text green
    r : text red
    i : text inensity
    B : background blue
    G : background green
    R : background red
    I : background intensity / blinking bit (selectable)
   (where I is the msb, b is the lsb)
</pre>
</p>
<p>
 This results in 2 selectable colors out of 16. The dark white on black code
is <c>0x07</c> (this is the bios/msdos default text color).
</p>
</body>
</section>
</chapter>

<chapter id="summary">
<title>Summary</title>
<section>
<body>
<p>
 For hardware info on how to program an ega/vga/svga video card, I suggest you
to read Ralph Brown&apos;s Interrupt List and Port List. It&apos;s avaible on the
internet, and contains all the technical details.
</p>
</body>
</section>
</chapter>
</guide>
