=== BackupTheBerlios/osdev/osxml/dtd/guide.dtd
<!-- $Id: guide.dtd,v 1.1 2002/07/02 07:43:37 zhware Exp $ -->

<!-- Grab a bunch of additional Latin characters courtesy of Norman -->
<!-- Walsh's extraction of the ISO 8879 set for DocBook XML. -->
<!ENTITY % ISOlat1.module "INCLUDE">
<![%ISOlat1.module;[
<!ENTITY % ISOlat1 PUBLIC
"ISO 8879:1986//ENTITIES Added Latin 1//EN//XML"
"iso-lat1.ent">
%ISOlat1;
<!--end of ISOlat1.module-->]]>
<!ENTITY nbsp "&#160;">		<!-- &nbsp; -->
<!ENTITY copy "&#169;">		<!-- (c) -->

<!ENTITY  % style.class	"b|box|brite|c|codenote|comment|e|i|path">
<!ENTITY  % link.class	"uri|homepage|email|mail">
<!ENTITY  % logic.class	"copyright|figure|fig|img|br|note|impo|warn|pre|p|table|ul|ol|new">
<!ENTITY  % all.class	"%logic.class;|%style.class;|%link.class;">

<!ELEMENT guide		(title, subtitle?, author+, abstract, version, date, copyright?, chapter+)>
<!ATTLIST guide		link CDATA #IMPLIED>
<!ELEMENT title		(#PCDATA|%style.class;)*>
<!ELEMENT subtitle	(#PCDATA)>
<!ELEMENT author	(#PCDATA|email|mail)*>
<!ATTLIST author	title CDATA #IMPLIED
                	homepage CDATA #IMPLIED>
<!ELEMENT abstract	(#PCDATA)>
<!ELEMENT version	(#PCDATA)>
<!ELEMENT date		(#PCDATA)>
<!ELEMENT copyright	(#PCDATA)>
<!ELEMENT chapter	(title, section+)>
<!ATTLIST chapter	id CDATA #IMPLIED>
<!ELEMENT section	(title?, body)>
<!ELEMENT body		(%all.class;)*>
<!ELEMENT figure	EMPTY>
<!ATTLIST figure	caption CDATA #IMPLIED
			short CDATA #IMPLIED
			link CDATA #REQUIRED>
<!ELEMENT fig		EMPTY>
<!ATTLIST fig		short CDATA #IMPLIED
			linkto CDATA #IMPLIED
			link CDATA #REQUIRED>
<!ELEMENT img		EMPTY>
<!ATTLIST img		src CDATA #REQUIRED>
<!ELEMENT br		(#PCDATA)>
<!ELEMENT new		(#PCDATA)>
<!ELEMENT note		(#PCDATA|%all.class;)*>
<!ATTLIST note		caption CDATA #IMPLIED>
<!ELEMENT impo		(#PCDATA|%all.class;)*>
<!ELEMENT warn		(#PCDATA|%all.class;)*>
<!ELEMENT pre		(#PCDATA|%all.class;)*>
<!ATTLIST pre		caption CDATA #IMPLIED
			link CDATA #IMPLIED>
<!ELEMENT p		(#PCDATA|%all.class;)*>
<!ELEMENT table		(tr+)>
<!ELEMENT tr		(th+|ti+)>
<!ELEMENT th		(#PCDATA|%all.class;)*>
<!ELEMENT ti		(#PCDATA|%all.class;)*>
<!ELEMENT ul		(li+)>
<!ELEMENT ol		(li+)>
<!ELEMENT li		(#PCDATA|%all.class;)*>

<!--STYLE TAGS-->
<!ELEMENT b		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT brite		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT box		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT c		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT codenote	(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT comment	(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT e		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT i		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT path		(#PCDATA|%style.class;|%link.class;)*>

<!--LINK TAGS-->
<!ELEMENT uri		(#PCDATA|%style.class;)*>
<!ATTLIST uri		link CDATA #IMPLIED>
<!ELEMENT homepage	(#PCDATA|%style.class;)*>
<!ELEMENT mail		(#PCDATA|%style.class;)*>
<!ATTLIST mail		link CDATA #REQUIRED>
<!ELEMENT email		(#PCDATA|%style.class;)*>
<!ATTLIST email		link CDATA #IMPLIED>

=== BackupTheBerlios/osdev/osxml/xml/cpuid.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd"
[
  <!ENTITY vendor.c SYSTEM "../src_esc/vendor.c.esc">
  <!ENTITY eax1.c SYSTEM "../src_esc/eax1.c.esc">
]>
<!-- $Id: cpuid.xml,v 1.1 2002/07/02 07:43:38 zhware Exp $ -->

<guide link="cpuid">
<title>CPUID &amp; Processor Identification</title>
<author>
<email link="sft3236@post.netlink.se">Jens Olsson</email>
<title>author</title>
</author>
<date>$Date: 2002/07/02 07:43:38 $</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2002/07/02 07:43:38 $</copyright>

<keywordset>
   <keyword>osdev</keyword>
   <keyword>Jens Olsson</keyword>
   <keyword>common</keyword>
   <keyword>CPU</keyword>
   <keyword>cpuid</keyword>
</keywordset>

<abstract>
The Pentium processors and later provide an instruction called CPUID for CPU
identification
</abstract>

<chapter id="intro">
<title>Introduction</title>
<section>
<body>
<p>
If you are programming an os and want to use all new features added to newer processors you will need  way to check which features the current processor is compatible with. To do this on the Pentium processors and later is easy since you are provided an instruction called CPUID for this purpose. On the 486 and older it's harder. although some 486 processors support the CPUID instruction, most of them doesn't. It is possible to check whether the processor is a 8086, 286, 386 or 486 without the CPUID instruction. This can be done in various ways where one of them is to execute an instruction which only works on the processor checked and later. If the processor encounters an instruction it can't handle, an invalid opcode exception wil be generated.
</p>
<p>
In this article we are going to go threw most of the things you need to do to identify your processor. 
</p>
</body>
</section>
</chapter>

<chapter id="no_pentium">
<title>Checking for 8086, 286, 386, 486 processors</title>
<section>
<body>
<p>
TODO
</p>
</body>
</section>
</chapter>

<chapter id="cpuid">
<title>The CPUID instruction</title>
<section>
<body>
<p>
The CPUID instruction is streightforward. The first you should do is to load EAX with 0. 
CPUID returns different values in EAX, EBX, ECX and EDX depending on the value in EAX before the call. 
When CPUID is executed with <c>EAX=0</c>, it will return the following:
</p>
<p>
<ul>
<li><b>EAX</b> --
The largest value EAX can be set to before executing the CPUID instruction. If it is, lets say 5, you can call CPUID 5 times more with <c>EAX=1</c> for the first, 2 for the second and so on.</li>
<li><b>EBX, EDX, ECX</b> --
These registers together forms the often called "vendor string".</li>
</ul>
</p>
<p>
Each processor manufacturer have their own vendor string. For example, Intels vendor string is "GenuineIntel" and AMD's vendor string is "AuthenticAMD" while old Cyrix uses "CyrixInstead". 
This is very important because the information retrieved if you call CPUID with <c>EAX&gt;0</c> is different between different manufacturers. 
</p>
<p>
We have to store all this information in some variables for future use. The following C++ example will execute the CPUID instruction with <c>EAX=0</c> and store the information retrieved in 2 variables.
</p>
<p>
<pre link="src/vendor.c">
&vendor.c;
</pre>
</p>
</body>
</section>
</chapter>

<chapter id="eax1">
<title>CPUID, EAX=1</title>
<section>
<body>
<p>
Now it gets even more interesting. If you execute CPUID while <c>EAX=1</c> instead you retrieve the processor family, model and stepping stored in EAX. You will also get a bitmap containing information on which functions (MMX, 3DNow etc.) that exists on the processor. Do not call CPUID with <c>EAX=1</c> if our variable, MaxEAX is less than 1. It is a bit more frustrating when using <c>EAX=1</c> because the processor manufacturers don't have the same meaning for the bits in the bitmap returned. Some are the same but many differ, we therefore have to check our VendorSign variable to determine how we should treat our bitmap. In this example we will make an array of all features in the bitmap that is correct for the Intel processor. We then check if AMD is used and change the array to the correct features. We will concentrate on Intel and AMD in this document. Adding support for Cyrix and other processors is left as an exercise for the reader;)
</p>
<p>
<pre link="src/eax1.c">
&eax1.c;
</pre>
</p>
</body>
</section>
</chapter>

<chapter id="todo">
<title>TODO</title>
<section>
<body>
<p>
<ul>
<li>Add information about L1 and L2 cache retrieved when <c>EAX=2</c>.</li>
<li>Add information about detecting CPUID instruction and determine pre CPUID processor types.</li>
</ul>
</p>
</body>
</section>
</chapter>

<chapter id="related">
<title>Related Sites</title>
<section>
<body>
<p>
<ul>
<li><uri link="http://www.intel.com/design/xeon/applnots/241618.htm">AP-485 Intel(c) Processor Identification and the CPUID Instruction</uri></li>
<li><uri link="http://www.sysid.subnet.dk/">Windows CPUID Utility</uri></li>
</ul>
</p>
</body>
</section>
</chapter>

</guide>

=== BackupTheBerlios/osdev/osxml/xml/template.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd"
[ 
   <!ENTITY hello.c SYSTEM "../src_esc/hello.c.esc">
]>
<!-- $Id: template.xml,v 1.1 2002/07/02 07:43:39 zhware Exp $ -->

<guide link="template">
<title>Template for OsDev XML Document</title>
<author title="author">
<email link="sto@zhware.net">Stoyan Zhekov</email>
</author>
<date>$Date: 2002/07/02 07:43:39 $</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2002/07/02 07:43:39 $</copyright>

<keywordset>
   <keyword>osdev</keyword>
   <keyword>Stoyan Zhekov</keyword>
   <keyword>template</keyword>
</keywordset>

<abstract>
I'll try to demonstrate all XML tags, available in the XML for OSDev documents.
</abstract>

<chapter id="para">
<title>Paragraphs</title>
<section>
<body>
<p>
This is one paragraph from the current chapter.
</p>
<p>
And this is the next paragraph.
</p>
</body>
</section>
<section>
<title>Style tags in the paragraphs</title>
<body>
<p>
Examples for <b>bold</b>, <i>italic</i>, <brite>brite</brite> <e>emphasis</e>.
</p>
<p>
But better is to describe <b>meanning</b> like: <c>user_finction()</c> or
<path>/path/to/some/file</path>.
</p>
</body>
</section>
<section>
<title>Second section</title>
<body>
Body of the second section.
</body>
</section>
</chapter>

<chapter>
<title>Chapter without id</title>
<section>
<title>First section</title>
<body>
The name and the link for this chapter is automaticaly generated.
</body>
</section>
</chapter>

<chapter id="notes">
<title>Notes, source code etc.</title>
<section>
<body>
<p>
<note>
This is example for note. The reading is optional.<br/>
But better is to read notes. Sometimes they provide
important information.
</note>
</p>
<p>
<note caption="Second note">
The first note was with a caption auto-generated. This one is with
entered caption.
</note>
</p>
<p>
<impo>
This is very, very important information! Must read!
</impo>
</p>
<p>
<warn>
If You start writing your documents in XML, you cannot stop. ;0):w
</warn>
</p>
</body>
</section>
<section>
<title>Source Code</title>
<body>
<p>
The most beautiful thing is auto generating of links to source codes and titles.
</p>
<p>
<pre>
int main()
{

}
</pre>
</p>
<p>
This source code is with entered caption and link to source code.
<pre caption="Hello world" link="src/hello.c">
&hello.c;
</pre>
</p>
</body>
</section>
</chapter>

<chapter id="lists">
<title>Lists</title>
<section>
<body>
<p>
In the documents you can use:
<ol>
<li>Numered lists</li>
<li>Unnumered lists</li> -- demonstrate also ia list in the other list
<ul>
<li>List Entry 1</li>
<li>List Entry 2</li>
</ul>
</ol>
</p>
</body>
</section>
</chapter>

<chapter id="urls">
<title>URLs</title>
<section>
<body>
<p>
The URLs are two types:
<ol>
<li>mail URLs -- <b>&lt;email&gt;</b>
<ul>
<li>unnamed mails:
<pre>
&lt;email&gt;author@example.com&lt;/email&gt; -> <email>author@example.com</email>
</pre>
</li>
<li>named emails:
<pre>
&lt;email link="author@example.com"&gt;The Autor&lt;/email&gt; -> <email link="author@example.com">The Author</email>
</pre>
</li>
</ul>
</li>
<li>link URLs -- <b>&lt;uri&gt;</b>
<ul>
<li>unnamed links:
<pre>
&lt;uri&gt;http://example.com/&lt;/uri&gt; -> <uri>http://example.com/</uri>
</pre>
</li>
<li>named links:
<pre>
&lt;uri link="http://example.com/"&gt;The Example Page&lt;/uri&gt; -> <uri link="http://example.com/">The Example Page</uri>
</pre>
</li>
</ul>
</li>
</ol>
<note>
<p>
<b>Notes</b>
</p>
<p>
<ol>
<li>
The original Gentoo's <b>&lt;mail&gt;</b> tags are also supported, but the difference is that the <b>@link</b> attribute for them is required, not optional.
</li>
<li>
There is also - &lt;homepage&gt; link <b>only in the
&lt;author&gt; tag</b> and it can be only unnamed link:
<pre>
&lt;author&gt;
<b>&lt;homepage&gt;http://example.com/&lt;/homepage&gt;</b>
&lt;/author&gt;
</pre>
</li>
</ol>
</p>
</note>
</p>
</body>
</section>
</chapter>

<chapter id="tables">
<title>Tables</title>
<section>
<body>
<p>
XML for OsDev understand only:
<ul>
<li><b>&lt;tr&gt;</b> for rows</li>
<li><b>&lt;th&gt;</b> for header cells</li>
<li><b>&lt;ti&gt;</b> for information cells</li>
</ul>
</p>
<p>
<table>
<tr>
<th>Header1</th>
<ti>Information</ti>
<ti>Information again</ti>
</tr>
<tr>
<th>Header2</th>
<ti>Information is most important thing.</ti>
<ti>More Information</ti>
</tr>
</table>
</p>
</body>
</section>
</chapter>

<chapter id="images">
<title>Images and Figures</title>
<section>
<body>
<p>
XML automaticaly generate figures caption and link to them.
<ul>
<li>Example for <b>&lt;img&gt;</b> tag.
<p>
<img src="img/thumb-fat-ide.jpg" border="1"/>
</p>
</li>
<li>But better is <b>&lt;figure&gt;</b> tag.
<p>
<figure link="img/fat-ide.jpg" caption="OSSO Screenshot" short=" osso screenshot"/>
</p>
</li>
<li>Figure with auto-generated caption.
<p>
<figure link="img/thumb-fat-ide.jpg"/>
</p>
</li>
<li>Figure without a caption (can link to something)
<p>
<fig link="img/thumb-fat-ide.jpg" linkto="img/fat-ide.jpg" short="screenshot" />
</p>
</li>
</ul>
</p>
</body>
</section>
</chapter>

</guide>

=== BackupTheBerlios/osdev/osxml/xml/spinlock_part3.xml
<?xml version='1.0'?>
<!DOCTYPE guide SYSTEM "../dtd/guide.dtd">
<!-- $Id: spinlock_part3.xml,v 1.1 2002/07/02 07:43:39 zhware Exp $ -->

<guide link="spinlock_part3">
<title>Spinlocks</title>
<subtitle>Part III</subtitle>
<author>
<email link="mrieker@o3one.org">Mike Rieker</email>
<title>author</title>
<homepage>http://www.o3one.org/</homepage>
</author>
<date>$Date: 2002/07/02 07:43:39 $</date>
<version>$Revision: 1.1 $</version>
<copyright>last updated $Date: 2002/07/02 07:43:39 $</copyright>

<keywordset>
   <keyword>osdev</keyword>
   <keyword>Mike Rieker</keyword>
   <keyword>scheduling</keyword>
   <keyword>spinlock</keyword>
</keywordset>

<abstract>
In some cases, there are simple and effective alternatives to spinlocks.
</abstract>

<chapter id="intro">
<title>Introduction</title>
<section>
<body>

<p>
In some cases, there are simple and effective alternatives to spinlocks.
</p>

</body>
</section>
</chapter>

<chapter id="inc_dec">
<title>Increment/Decrement</title>
<section>
<body>

<p>
Consider the case:
<pre>
void dec_thread_refcount (Thread *thread)

{
  int new_refcount;

  acquire_spinlock (&amp;(thread -> spinlock));  // lock access to thread -> refcount
  new_refcount = -- (thread -> refcount);    // decrement it, save new value
  release_spinlock (&amp;(thread -> spinlock));  // unlock
  if (new_refcount == 0) kfree (thread);     // if no one is using it anymore, free it
}
</pre>
</p>
<p>
Seems like a lot of work acquiring and releasing the spinlock just to decrement the 
refcount.  Well, remember the <c>'lock' prefix instruction</c> we used to make the test_and_set 
thing?  We can be a little fancier about it and make a <c>'dec_and_testz' routine</c>:
<pre>
  int locked_dec_and_testz (int *refcount);  // decrement *refcount, return whether or not it went zero

    .globl locked_dec_and_testz
  locked_dec_and_testz:
    xorl %eax,%eax    # clear all of %eax
    movl 4(%esp),%edx # get pointer to refcount
    lock              # keep other cpu's out of next instruction
    decl (%edx)       # decrement refcount, keeping other cpu's out of refcount
    setz %al          # set %eax=1 if result is zero, set %eax=0 otherwise
    ret               # return %eax as the result
</pre>
</p>
<p>
So now we can write:
<pre>
void dec_thread_refcount (Thread *thread)

{
  if (locked_dec_and_testz (&amp;(thread -> refcount)) {
    kfree (thread);
  }
}
</pre>
</p>
<p>
Now this has a little gotcha.  <c>'refcount'</c> must now be thought of as being a variable 
not protected by a spinlock, but by 'lock instruction prefix' access only!  So any 
modifications to refcount must be done with the lock prefix.  So we can no longer:
<pre>
  acquire_spinlock (&amp;(thread -> spinlock));
  (thread -> refcount) ++;
  release_spinlock (&amp;(thread -> spinlock));
</pre>
... because the locked_dec_and_testz routine might be in progress on another cpu, and 
our 'spinlock' won't do anything to stop it!
</p>
<p>
So we have to supply a 'locked_inc' routine:
<pre>
  void locked_inc (int *refcount);

    .globl locked_inc
  locked_inc:
    movl 4(%esp),%edx
    lock
    incl (%edx)
    ret
</pre>
</p>
<p>
But we still come out ahead, because there is no possibility of doing any spinning in 
any of these routines.  (The actual spinning is done at the CPU bus level, which is 
very very fast).
</p>

</body>
</section>
</chapter>

<chapter id="atomic">
<title>Atomic arithmetic</title>
<section>
<body>

<p>
Now we can generally apply increment/decrement to any single arithmetic operation on 
a single variable.  It is possible to write routines to do add, subtract, or, and, xor, 
etc, and have the routine return the previous value.
</p>
<p>
For example, this routine or's in <c>'new_bits'</c> into *value, and returns the 
previous contents of value:
<pre>
  int atomic_or_rtnold (int new_bits, int *value);

    .globl atomic_or_rtnold
  atomic_or_rtnold:
    movl 8(%esp),%edx    # point to value
    movl (%edx),%eax     # sample the current contents of value
  atomic_or_loop:
    movl 4(%esp),%ecx    # get the new_bits
    orl  %eax,%ecx       # or them together
    lock                 # bus lock the next instruction
    cmpxchgl %ecx,(%edx) # if 'value' hasn't changed, store our new value there
    jne atomic_or_loop   # repeat if 'value' has changed
    ret                  # return with old (sampled) contents of value
</pre>
</p>
<p>
Now you notice this does have a little 'spin' in it, it has a loop back.  But the 
loop is so short, that the chances of conflicting with other modifications of the 
*value is very slim, so it is highly unlikely that it will ever loop.
</p>
<p>
If we don't want the old value, we can do this:
<pre>
  void atomic_or (int new_bits, int *value);

    .globl atomic_or
  atomic_or:
    movl 4(%esp),%eax    # get the new_bits
    movl 8(%esp),%edx    # point to value
    lock                 # bus lock the next instruction
    orl  %eax,(%edx)     # update value
    ret
</pre>
... and not have any loop in there at all.
</p>

</body>
</section>
</chapter>

<chapter id="stack">
<title>Atomic linked stack</title>
<section>
<body>

<p>
You can get 'nasty' and implement a LIFO linked stack with atomic operations.
</p>
<p>
Suppose we have:
<pre>
  typedef struct Block Block;
  struct Block { Block *next_block;
                  ...
               };

  static Block *free_blocks = NULL;

  void free_a_block (Block *block_to_free)

  {
    Block *old_top_free_block;

    do {
      old_top_free_block = free_blocks;
      block_to_free = old_top_free_block;
    } while (!atomic_setif_ptr (&amp;free_blocks, block_to_free, old_top_free_block));
  }

  atomic_setif_ptr says:

    if (free_blocks != old_top_free_block) return (0);
    else {
      free_blocks = block_to_free;
      return (1);
    }

    .globl atomic_setif_ptr
  atomic_setif_ptr:
    movl  4(%esp),%edx    # get pointer to free_blocks
    movl  8(%esp),%ecx    # get block_to_free
    movl 12(%esp),%eax    # get old_free_top_block
    lock                  # bus lock the next instruction
    cmpxchgl %ecx,(%edx)  # if free_blocks == old_free_top_block, then free_blocks = block_to_free
    jne atomic_setif_failed
    movl $1,%eax          # success, return 1
    ret
  atomic_setif_failed:
    xorl %eax,%eax        # failure, return 0
    ret
</pre>
</p>
<p>
  Now we can use that same routine to write the alloc routine:
<pre>
  Block *alloc_a_block (void)

  {
    Block *sample_block;

    do {
      sample_block = free_blocks;
      if (sample_block == NULL) break;
    } while (!atomic_setif_ptr (&amp;free_blocks, sample_block -> next_block, sample_block));
    return (sample_block);
  }
</pre>
</p>
<p>
But again, the gotcha is that 'free_blocks' can only be modified with atomic operations.  
So if you must also scan the list, you will have to use a spinlock.
</p>

</body>
</section>
</chapter>

<chapter id="summary">
<title>Summary</title>
<section>
<body>

<p>
Simple spinlocked sequences can be replaced with atomic operations and can 
result in performance improvements.  Now you have more fun stuff to play with!
</p>

</body>
</section>
</chapter>

</guide>
